version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: haccpboard-nginx
    ports:
      - 7001:80
    links:
      - php
    depends_on:
      - php
    volumes:
      - "./nginx:/etc/nginx/conf.d/"
      - ".:/app"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haccpboard-php
    volumes:
      - ".:/app"
  
  mysql:
    image: mysql:5.6
    container_name: haccpboard-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: haccp-dashboard
    ports:
      - "3308:3306"
